### ISSUE TITLE
panic when building mutagen 0.1.1 with rust nightly

### ISSUE THREAD

**Issue by OddBloke** [llogiq/mutagen#124]
On a completely fresh project with mutagen as a dev-dependency:

```
$ grep -B1 mutagen Cargo.toml
[dev-dependencies]
mutagen = "0.1.1"
```

I see the following error when I run anything that attempts to build mutagen:

```
% RUST_BACKTRACE=1 cargo test
   Compiling mutagen v0.1.1
error: failed to run custom build command for `mutagen v0.1.1`
process didn't exit successfully: `/home/daniel/personal_dev/tmp/target/debug/build/mutagen-28d4cc400087a244/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: rust_begin_unwind
             at libstd/panicking.rs:337
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:92
   8: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  10: build_script_build::main
             at ./build.rs:425
  11: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  16: main
  17: __libc_start_main
  18: _start
```

This was happening with nightly in the middle of last week (which was when I first attempted to use mutagen), and on the latest nightly build:

```
$ rustup show
Default host: x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.28.0-nightly (e3bf634e0 2018-06-28)
```

**Comment by gnieto** [comment]
Hi, thanks for reporting.

This seems related to a bug related with the build script. Some days ago, this script was changed and this will probably be fixed on the next release.

@llogiq if you can create a new release, I can check  if this is solved on that new version
