### ISSUE TITLE
ICE on function with macro call

### ISSUE THREAD

**Issue by orium** [llogiq/mutagen#22]
ICE when trying to mutate the following function:

```rust
#[cfg_attr(test, mutate)]
pub fn foo() -> () {
    debug_assert!(true);
}
```

The output of `rustc` is

```text
thread 'rustc' panicked at 'fold_mac disabled by default', libsyntax/fold.rs:184:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:206
   3: std::panicking::default_hook
             at libstd/panicking.rs:222
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:400
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:363
   6: syntax::fold::Folder::fold_mac
             at /home/orium/programming/projects/mutagen/plugin/<panic macros>:3
   7: syntax::fold::noop_fold_stmt_kind::{{closure}}
             at /checkout/src/libsyntax/fold.rs:1364
   8: <syntax::ptr::P<T>>::map
             at /checkout/src/libsyntax/ptr.rs:88
   9: syntax::fold::noop_fold_stmt_kind
             at /checkout/src/libsyntax/fold.rs:1363
  10: syntax::fold::noop_fold_stmt
             at /checkout/src/libsyntax/fold.rs:1348
  11: mutagen_plugin::fold_first_block::{{closure}}::{{closure}}
             at /home/orium/programming/projects/mutagen/plugin/src/lib.rs:512
  12: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
             at /checkout/src/libcore/ops/function.rs:271
  13: <core::option::Option<T>>::map
             at /checkout/src/libcore/option.rs:404
  14: <core::iter::FlatMap<I, U, F> as core::iter::iterator::Iterator>::next
             at /checkout/src/libcore/iter/mod.rs:2448
  15: <alloc::vec::Vec<T>>::extend_desugared
             at /checkout/src/liballoc/vec.rs:1906
  16: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::spec_extend
             at /checkout/src/liballoc/vec.rs:1803
  17: <alloc::vec::Vec<T> as core::iter::traits::Extend<T>>::extend
             at /checkout/src/liballoc/vec.rs:1767
  18: mutagen_plugin::fold_first_block::{{closure}}
             at /home/orium/programming/projects/mutagen/plugin/src/lib.rs:509
  19: <syntax::ptr::P<T>>::map
             at /checkout/src/libsyntax/ptr.rs:88
  20: mutagen_plugin::fold_first_block
             at /home/orium/programming/projects/mutagen/plugin/src/lib.rs:499
  21: <mutagen_plugin::MutatorPlugin<'a, 'cx> as syntax::fold::Folder>::fold_item_kind
             at /home/orium/programming/projects/mutagen/plugin/src/lib.rs:204
  22: syntax::fold::noop_fold_item_simple
             at /checkout/src/libsyntax/fold.rs:1064
  23: syntax::fold::Folder::fold_item_simple
             at /checkout/src/libsyntax/fold.rs:72
  24: syntax::fold::noop_fold_item::{{closure}}
             at /checkout/src/libsyntax/fold.rs:1053
  25: <syntax::ptr::P<T>>::map
             at /checkout/src/libsyntax/ptr.rs:88
  26: syntax::fold::noop_fold_item
             at /checkout/src/libsyntax/fold.rs:1053
  27: syntax::fold::Folder::fold_item
             at /checkout/src/libsyntax/fold.rs:68
  28: mutagen_plugin::mutator
             at /home/orium/programming/projects/mutagen/plugin/src/lib.rs:46
  29: core::ops::function::Fn::call
             at /checkout/src/libcore/ops/function.rs:73
  30: <F as syntax::ext::base::MultiItemModifier>::expand
             at /checkout/src/libsyntax/ext/base.rs:157
  31: syntax::ext::expand::MacroExpander::expand_invoc
  32: syntax::ext::expand::MacroExpander::expand
  33: syntax::ext::expand::MacroExpander::expand_crate
  34: rustc_driver::driver::phase_2_configure_and_expand_inner::{{closure}}
  35: rustc_driver::driver::phase_2_configure_and_expand_inner
  36: rustc_driver::driver::compile_input
  37: rustc_driver::run_compiler

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.25.0-nightly (27a046e93 2018-02-18) running on x86_64-unknown-linux-gnu
```

**Comment by llogiq** [comment]
I have solved this already for flamer and overflower – will port my fix to mutagen when I get around to it.

**Comment by llogiq** [comment]
Current master should work. Please check & re-open if it doesn't. Thank you.

**Comment by orium** [comment]
Still have the same bug (reproducible in the same way).

**Comment by orium** [comment]
Ping to reopen @llogiq
